---
# Curl isn't installed, needed for tests

- name: Prepare
  hosts: all

  tasks:
    - name: install curl
      become: true
      apt:
        name: curl
        state: present
    - name: install gnupg
      become: true
      apt:
        name: gnupg
        state: present
