---
# Curl isn't installed, needed for tests

- name: Prepare
  hosts: all

  tasks:
    # - name: install curl
    #   become: true
    #   apt:
    #     name: curl
    #     state: present
    - name: Install pckgs
      become: true
      action: apt-get pkg={{ item }} state=present
      with_items:
        - acl
        - python3-pip
        - curl
