---
# Curl isn't installed, needed for tests

- name: Prepare
  hosts: all

  tasks:
    # - name: install curl
    #   become: true
    #   apt:
    #     name: curl
    #     state: present
    - name: Install pckgs
      become: true
      apt:
        name: curl
        state: latest
        update_cache: yes
        upgrade: yes
